apiVersion: v1
data:
  SERVER_PROFILE_URL: https://www.github.com/pingidentity/pingidentity-server-profiles.git
  SERVER_PROFILE_PATH: getting-started/pingfederate
  PING_IDENTITY_ACCEPT_EULA: "YES"
  JETTY_THREAD_MIN: "10"
  JETTY_THREAD_MAX: "200"
  JVM_HEAP_MIN: "512m"
  JVM_HEAP_MAX: "1024m"
kind: ConfigMap
metadata:
  name: standalone-variables
