apiVersion: apps/v1
kind: Deployment
metadata:
  name: pf-cluster-engine
  labels:
    app: pf-cluster
    tier: engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pf-cluster
      tier: engine
  template:
    metadata:
      labels:
        app: pf-cluster
        tier: engine
        revision: init
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: engine-variables
            - configMapRef:
                name: private-variables
            - secretRef:
                name: devops-secret
                optional: true
            - configMapRef:
                name: jolokia-variables
          name: engine-node
          image: gcr.io/ping-identity/pingfederate:10.0.0-Beta-centos-edge
          ports:
            - containerPort: 9031
          resources:
            requests:
              memory: 16Gi
              cpu: "12"
            limits:
              memory: 16Gi
              cpu: "12"
#        - env:
#            - name: HOSTNAME
#              valueFrom:
#                fieldRef:
#                  fieldPath: spec.nodeName
#          envFrom:
#            - configMapRef:
#                name: telegraf-variables
#          image: docker.io/library/telegraf:1.9.5-alpine
#          name: telegraf
#          resources:
#            limits:
#              memory: 500Mi
#            requests:
#              cpu: 500m
#              memory: 500Mi
#          volumeMounts:
#            - mountPath: /etc/telegraf
#              name: telegraf-conf
#      volumes:
#        - configMap:
#            name: telegraf-conf
#          name: telegraf-conf
